Repository bifrost-vui/bifrost-front-end-library, pull requests merged in 2021-11, with the labels that each got.

#199 DS-193-Bug-tab-on-mobile
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/tab/scss/index.scss
  projects/front-end-library/src/lib/scss/base/_base.scss
  projects/front-end-library/src/lib/scss/themes/videotron/_color.scss
Labels: ready to merge, tested

#201 DS 196 - fix icon stretched in card
  projects/front-end-library/src/lib/components/card/scss/index.scss
Labels: Ready for review

#198 Ds 168 upgrade angular 12 2 1
  .storybook/main.js
  .storybook/preview.ts
  build-storybook.log
  package-lock.json
  package.json
  projects/front-end-library/src/_doc/1-Introduction/1-introduction.stories.mdx
  projects/front-end-library/src/_doc/1-Introduction/2-changelog.stories.mdx
  projects/front-end-library/src/_doc/1-Introduction/3-contribute.stories.mdx
  projects/front-end-library/src/_doc/1-Introduction/4-merge-checklist.stories.mdx
  projects/front-end-library/src/_doc/1-Introduction/5-components-list.stories.mdx
  projects/front-end-library/src/_doc/2-Implementation/3-angular.stories.mdx
  projects/front-end-library/src/_doc/2-Implementation/4-drupal.stories.mdx
  projects/front-end-library/src/_doc/2-Implementation/5-drupal-filters.stories.mdx
  projects/front-end-library/src/_doc/2-Implementation/5-theme.stories.mdx
  projects/front-end-library/src/_doc/migrations/1-icon-migration.stories.mdx
  projects/front-end-library/src/_doc/styles/1-colors.stories.mdx
  projects/front-end-library/src/_doc/styles/3-spacing.stories.mdx
  projects/front-end-library/src/_doc/styles/4-icons.stories.mdx
  projects/front-end-library/src/_doc/styles/5-shadow.stories.mdx
  projects/front-end-library/src/_doc/styles/6-borderRadius.stories.mdx
  projects/front-end-library/src/_doc/styles/7-typography.stories.mdx
  projects/front-end-library/src/_doc/styles/typography/doc.stories.mdx
  projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/banner/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/block-highlight/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/block-selection/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/breadcrumb/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/button-icon/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/button-nav/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/card/_doc/plan-api-exposed.stories.mdx
  projects/front-end-library/src/lib/components/carousel/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/hero/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/icon/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/input-increment/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/input-search/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/link/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/list/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/logo/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/navigation-footer/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/navigation-header/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/price/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/row-button/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/slideshow/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/tab/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/tile/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/js/bifrost-components.js
  projects/front-end-library/src/lib/js/demo/bifrost/carousel.js
  projects/front-end-library/src/lib/main.twig
  projects/front-end-library/src/lib/scss/dependencies/bootstrap/_bootstrap_variables.scss
  projects/front-end-library/src/utils/twig-container/twig-container.component.ts
  scripts/generate/templates/component/_doc/doc.stories.mdx
  webpack.config.js
Labels: tested

#143 components/DS-124-badge-in-button-icon
  .storybook/preview-head.html
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/badge/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/badge/angular/badge.component.ts
  projects/front-end-library/src/lib/components/badge/scss/index.scss
  projects/front-end-library/src/lib/components/badge/twig/index.twig
  projects/front-end-library/src/lib/components/button-icon/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/button-icon/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/button-icon/angular/button-icon.component.ts
  projects/front-end-library/src/lib/components/button-icon/scss/index.scss
  projects/front-end-library/src/lib/components/button-icon/twig/index.twig
  projects/front-end-library/src/lib/scss/themes/videotron/_color.scss
Labels: tested

#203 Ds 199 new combo card variant
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/card/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/card/angular/card.component.ts
  projects/front-end-library/src/lib/components/card/scss/index.scss
  projects/front-end-library/src/lib/components/card/twig/combo.twig
  projects/front-end-library/src/lib/components/card/twig/index.twig
Labels: ready to merge, tested

#148 DS-107 text 2 lines
  projects/front-end-library/src/lib/components/block-selection/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/block-selection/scss/index.scss
  projects/front-end-library/src/lib/components/block-selection/twig/index.twig
  projects/front-end-library/src/lib/components/price/_doc/all-prices.drupal.twig
  projects/front-end-library/src/lib/components/price/angular/price.component.ts
  projects/front-end-library/src/lib/components/price/scss/index.scss
  projects/front-end-library/src/lib/components/price/twig/index.twig
Labels: Ready for review

#202 DS-204-invalid-html-attribute-in-cards - fix
  projects/front-end-library/src/lib/components/card/scss/index.scss
  projects/front-end-library/src/lib/components/card/twig/index.twig
Labels: ready to merge

#205 Ds 198 add promotion badges in phone, plan and combo cards
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/card/_doc/plan-api-exposed.stories.mdx
  projects/front-end-library/src/lib/components/card/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/card/angular/card.component.ts
  projects/front-end-library/src/lib/components/card/scss/index.scss
  projects/front-end-library/src/lib/components/card/twig/combo.twig
  projects/front-end-library/src/lib/components/card/twig/increment.twig
  projects/front-end-library/src/lib/components/card/twig/index.twig
  projects/front-end-library/src/lib/components/card/twig/phone.twig
  projects/front-end-library/src/lib/components/card/twig/plan.twig
  projects/front-end-library/src/lib/components/card/twig/protection.twig
Labels: Ready for review

#211 DS-210-Badge-disabled-layout
  projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/badge/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/badge/scss/index.scss
Labels: tested

#206 ds-197-Added title in Price Promotion
  projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/card/_doc/plan-api-exposed.stories.mdx
  projects/front-end-library/src/lib/components/price/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/price/_doc/null.drupal.twig
  projects/front-end-library/src/lib/components/price/angular/price.component.ts
  projects/front-end-library/src/lib/components/price/scss/index.scss
  projects/front-end-library/src/lib/components/price/twig/index.twig
Labels: tested

#195 DS-165-range-slider
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/input-slider/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/input-slider/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/input-slider/angular/input-slider.component.html
  projects/front-end-library/src/lib/components/input-slider/angular/input-slider.component.ts
  projects/front-end-library/src/lib/components/input-slider/js/index.js
  projects/front-end-library/src/lib/components/input-slider/scss/index.scss
  projects/front-end-library/src/lib/components/input-slider/twig/index.twig
  projects/front-end-library/src/lib/js/bifrost-components.js
  projects/front-end-library/src/lib/scss/index.scss
Labels: Ready for review

#193 ds-188 - Small fixes
  projects/front-end-library/src/lib/components/breadcrumb/angular/breadcrumb.component.ts
  projects/front-end-library/src/lib/components/card/angular/card.component.ts
  projects/front-end-library/src/lib/components/hero/angular/hero.component.ts
  projects/front-end-library/src/lib/components/icon/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/navigation-footer/angular/footer.component.ts
  projects/front-end-library/src/lib/components/navigation-footer/twig/index.twig
  projects/front-end-library/src/lib/components/price/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/price/_doc/template-all.drupal.twig
  projects/front-end-library/src/lib/components/price/_doc/template-null.drupal.twig
  projects/front-end-library/src/lib/components/price/angular/api.model.ts
  projects/front-end-library/src/lib/components/price/angular/price.component.ts
Labels: Ready for review

#210 ds-189-adjust slideshow height
  projects/front-end-library/src/lib/components/slideshow/_doc/data.ts
  projects/front-end-library/src/lib/components/slideshow/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/slideshow/js/index.js
  projects/front-end-library/src/lib/components/slideshow/scss/index.scss
Labels: tested
