Repository bifrost-vui/bifrost-front-end-library, pull requests merged in 2021-12, with the labels that each got.

#218 Ds 212 improve slider ux
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/input-slider/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/input-slider/js/index.js
  projects/front-end-library/src/lib/components/input-slider/scss/index.scss
  projects/front-end-library/src/lib/components/input-slider/twig/index.twig
Labels: ready to merge, tested

#229 Ds 239 fix navigation header on mobile
  projects/front-end-library/src/lib/components/button-icon/angular/button-icon.component.ts
  projects/front-end-library/src/lib/components/button-icon/twig/index.twig
  projects/front-end-library/src/lib/components/navigation-header/scss/index.scss
  projects/front-end-library/src/lib/components/navigation-header/twig/mega-menu.twig
Labels: tested

#222 DS-221 - Badge is Multiline
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/badge/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/badge/angular/badge.component.ts
  projects/front-end-library/src/lib/components/badge/scss/index.scss
  projects/front-end-library/src/lib/components/badge/twig/index.twig
  projects/front-end-library/src/lib/components/card/scss/index.scss
Labels: tested

#232 v1-5-1
  CHANGELOG.mdx
  projects/front-end-library/package.json
  projects/front-end-library/src/lib/components/badge/scss/index.scss
  projects/front-end-library/src/lib/components/banner/twig/index.twig
  projects/front-end-library/src/lib/components/button-icon/scss/index.scss
Labels: tested

#224 DS 195 Sort-controls-by-alphanumeric-order
  .storybook/preview.ts
Labels: ready to merge

#223 DS-219 improve link component
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/link/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/link/_doc/template-css-only.drupal.twig
  projects/front-end-library/src/lib/components/link/_doc/template-examples.drupal.twig
  projects/front-end-library/src/lib/components/link/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/link/angular/link.component.html
  projects/front-end-library/src/lib/components/link/angular/link.component.ts
  projects/front-end-library/src/lib/components/link/scss/index.scss
  projects/front-end-library/src/lib/components/link/twig/back-to-top.twig
  projects/front-end-library/src/lib/components/link/twig/index.twig
  projects/front-end-library/src/lib/components/navigation-footer/twig/footer-legal.twig
  projects/front-end-library/src/lib/components/navigation-footer/twig/footer-main.twig
Labels: Ready for review
