Repository bifrost-vui/bifrost-front-end-library, pull requests merged in 2022-01, with the labels that each got.

#238 DS-256 fix flex hero responsiveness buttton
  .storybook/preview.ts
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/button/scss/index.scss
  projects/front-end-library/src/lib/components/hero/twig/index.twig
Labels: ready to merge, tested

#248 v1.5.2
  CHANGELOG.mdx
  projects/front-end-library/package.json
  projects/front-end-library/src/lib/components/button-nav/_doc/usage-example.drupal.twig
  projects/front-end-library/src/lib/components/button-nav/scss/index.scss
  projects/front-end-library/src/lib/components/button/scss/index.scss
  projects/front-end-library/src/lib/components/button/twig/index.twig
  projects/front-end-library/src/lib/components/hero/twig/index.twig
  projects/front-end-library/src/lib/components/slideshow/_doc/data.ts
  projects/front-end-library/src/lib/components/slideshow/js/index.js
Labels: ready to merge, tested

#227 DS-234 improve global styles
  projects/front-end-library/src/_doc/styles/1-colors.stories.mdx
  projects/front-end-library/src/_doc/styles/3-spacing.stories.mdx
  projects/front-end-library/src/_doc/styles/5-shadow.stories.mdx
  projects/front-end-library/src/_doc/styles/6-borderRadius.stories.mdx
  projects/front-end-library/src/_doc/styles/7-typography.stories.mdx
  projects/front-end-library/src/_doc/styles/typography/doc.stories.mdx
  projects/front-end-library/src/_doc/styles/typography/headings.drupal.twig
  projects/front-end-library/src/_doc/styles/typography/interface-display.drupal.twig
  projects/front-end-library/src/_doc/styles/typography/paragraphs.drupal.twig
  projects/front-end-library/src/lib/_doc/1-Introduction/1-introduction.stories.mdx
  projects/front-end-library/src/lib/_doc/1-Introduction/2-changelog.stories.mdx
  projects/front-end-library/src/lib/_doc/1-Introduction/3-contribute.stories.mdx
  projects/front-end-library/src/lib/_doc/1-Introduction/4-merge-checklist.stories.mdx
  projects/front-end-library/src/lib/_doc/1-Introduction/5-components-list.stories.mdx
  projects/front-end-library/src/lib/_doc/2-Implementation/3-angular.stories.mdx
  projects/front-end-library/src/lib/_doc/2-Implementation/4-drupal.stories.mdx
  projects/front-end-library/src/lib/_doc/2-Implementation/5-drupal-filters.stories.mdx
  projects/front-end-library/src/lib/_doc/2-Implementation/5-theme.stories.mdx
  projects/front-end-library/src/lib/_doc/2-Implementation/6-reversed-and-highlight.stories.mdx
  projects/front-end-library/src/lib/_doc/migrations/1-icon-migration.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
  projects/front-end-library/src/lib/_doc/styles/1-colors/doc.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/2-spacings/doc.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/2-spacings/spacings.js
  projects/front-end-library/src/lib/_doc/styles/3-headings/doc.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/3-headings/examples.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/3-headings/headings.drupal.twig
  projects/front-end-library/src/lib/_doc/styles/3-headings/headings.js
  projects/front-end-library/src/lib/_doc/styles/4-typography/doc.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/4-typography/typography.js
  projects/front-end-library/src/lib/_doc/styles/5-icons/icons.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/6-borderRadius/borderRadius.js
  projects/front-end-library/src/lib/_doc/styles/6-borderRadius/doc.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/7-shadows/doc.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/7-shadows/shadows.js
Labels: tested

#217 DS-207
  projects/front-end-library/src/lib/components/selection-tile/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/selection-tile/_doc/example.drupal.twig
  projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
  projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
  projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
Labels: ready to merge, in review design, tested
