Repository bifrost-vui/bifrost-front-end-library, pull requests merged in 2022-12, with the labels that each got.

#323 Ds 341 update documentation about drupal implementation
  CONTRIBUTING.mdx
  projects/front-end-library/src/lib/_doc/1-Introduction/1-introduction.stories.mdx
  projects/front-end-library/src/lib/_doc/1-Introduction/5-components-list.mdx
  projects/front-end-library/src/lib/_doc/2-Implementation/3-angular.stories.mdx
  projects/front-end-library/src/lib/_doc/2-Implementation/4-drupal.stories.mdx
  projects/front-end-library/src/lib/_doc/2-Implementation/5-theme.stories.mdx
  projects/front-end-library/src/lib/_doc/2-Implementation/6-reversed-and-highlight.stories.mdx
  projects/front-end-library/src/lib/_doc/2-Implementation/7-icon-migration.stories.mdx
  projects/front-end-library/src/lib/_doc/showcases/showcases-drupal.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/1-colors/doc.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/5-icons/icons.stories.mdx
  projects/front-end-library/src/lib/components/breadcrumb/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/breadcrumb/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/carousel/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/carousel/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/input-increment/js/index.js
  projects/front-end-library/src/lib/js/bifrost-components.js
  projects/front-end-library/src/lib/main.twig
  projects/front-end-library/src/lib/scss/dependencies/bootstrap/_bootstrap_variables.scss
  projects/front-end-library/src/lib/scss/index.scss
  projects/front-end-library/src/lib/validation.twig
Labels: tested

#196 DS-190: Start legal copyright and distribution
  README.md
  projects/front-end-library/src/lib/_doc/1-Introduction/1-introduction.stories.mdx
Labels: documentation

#376 DS-452: Preview link improvement
  .storybook/manager-head.html
  package-lock.json
  package.json
  public/favicon/bifrost.ico
  public/favicon/bifrost.png
  webpack.config.js
Labels: tested

#384 DS-376: Set Card Title to be a object with 2 part
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/card/_doc/plan-api-exposed.stories.mdx
  projects/front-end-library/src/lib/components/card/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/card/angular/card.component.ts
  projects/front-end-library/src/lib/components/card/twig/index.twig
Labels: ready to merge, tested

#386 DS-456: establish the Onboarding documentation
  projects/front-end-library/src/lib/_doc/3- Onboarding/01- introduction.stories.mdx
  projects/front-end-library/src/lib/_doc/3- Onboarding/03- kind-of-wiki.stories.mdx
  projects/front-end-library/src/lib/_doc/3- Onboarding/05- designer.stories.mdx
  projects/front-end-library/src/lib/_doc/3- Onboarding/10- developer.stories.mdx
  projects/front-end-library/src/lib/_doc/3- Onboarding/12- jira-project-explanation.stories.mdx
  projects/front-end-library/src/lib/_doc/3- Onboarding/15- Process.stories.mdx
  projects/front-end-library/src/lib/_doc/5-Implementation/3-angular.stories.mdx
  projects/front-end-library/src/lib/_doc/5-Implementation/4-drupal.stories.mdx
  projects/front-end-library/src/lib/_doc/5-Implementation/5-drupal-filters.stories.mdx
  projects/front-end-library/src/lib/_doc/5-Implementation/5-theme.stories.mdx
  projects/front-end-library/src/lib/_doc/5-Implementation/6-reversed-and-highlight.stories.mdx
  projects/front-end-library/src/lib/_doc/5-Implementation/7-icon-migration.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/1-colors/doc.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/2-spacings/doc.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/4-typography/doc.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/5-icons/icons.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/6-borderRadius/doc.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/7-shadows/doc.stories.mdx
Labels: documentation, tested

#385 DS-400
  projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
Labels: documentation, ready to merge, tested
