Repository bifrost-vui/bifrost-front-end-library, pull requests merged in 2022-04, with the labels that each got.

#273 ds-294 fix reversed and highlight
  CHANGELOG.mdx
  projects/front-end-library/src/lib/_doc/2-Implementation/6-reversed-and-highlight.stories.mdx
  projects/front-end-library/src/lib/components/hero/twig/index.twig
  projects/front-end-library/src/lib/scss/dependencies/bifrost/_global.scss
  projects/front-end-library/src/lib/scss/themes/videotron/_color.scss
Labels: tested

#274 ds-289-create-angular-icons
  .gitignore
  .storybook/preview-head.html
  CHANGELOG.mdx
  package.json
  projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/badge/_doc/template.angular.component.html
  projects/front-end-library/src/lib/components/badge/_doc/template.angular.component.ts
  projects/front-end-library/src/lib/components/badge/_doc/template.angular.module.ts
  projects/front-end-library/src/lib/components/badge/_doc/template.angular.ts
  projects/front-end-library/src/lib/components/badge/angular/badge.component.html
  projects/front-end-library/src/lib/components/badge/angular/badge.component.ts
  projects/front-end-library/src/lib/components/badge/angular/badge.module.ts
  projects/front-end-library/src/lib/components/badge/scss/index.scss
  projects/front-end-library/src/lib/components/badge/twig/index.twig
  projects/front-end-library/src/lib/components/icon/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/icon/_doc/template.angular.component.html
  projects/front-end-library/src/lib/components/icon/_doc/template.angular.component.ts
  projects/front-end-library/src/lib/components/icon/_doc/template.angular.module.ts
  projects/front-end-library/src/lib/components/icon/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/icon/angular/icon.component.html
  projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
  projects/front-end-library/src/lib/components/icon/angular/icon.module.ts
  projects/front-end-library/src/lib/components/icon/twig/index.twig
  projects/front-end-library/src/public-api.ts
  projects/showcase-angular/src/app/app.component.html
  projects/showcase-angular/src/app/app.component.ts
  projects/showcase-angular/src/app/app.module.ts
  projects/showcase-angular/tsconfig.app.json
  scripts/generate-svg-ts/index.js
  scripts/generate/templates/component/_doc/doc.stories.mdx
  scripts/generate/templates/component/_doc/template.angular.component.html
  scripts/generate/templates/component/_doc/template.angular.component.ts
  scripts/generate/templates/component/_doc/template.angular.module.ts
  scripts/generate/templates/component/angular/component-name.component.spec.ts
  scripts/generate/templates/component/angular/component-name.component.ts
Labels: Ready for review

#290 ds-315 improve banner advanced
  projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/banner-advanced/scss/index.scss
  projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
Labels: tested

#262 DS-290- Progress-Multi Component
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/progress-multi/_doc/data.ts
  projects/front-end-library/src/lib/components/progress-multi/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/progress-multi/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/progress-multi/angular/progress-multi.component.html
  projects/front-end-library/src/lib/components/progress-multi/angular/progress-multi.component.ts
  projects/front-end-library/src/lib/components/progress-multi/angular/progress-multi.module.ts
  projects/front-end-library/src/lib/components/progress-multi/twig/index.twig
  projects/front-end-library/src/lib/scss/dependencies/bootstrap/_bootstrap_variables.scss
  projects/front-end-library/src/lib/scss/dependencies/bootstrap/overwrite/_progress.scss
Labels: tested

#252 DS-265 - Input checkbox (component)
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/input-checkbox/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/input-checkbox/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/input-checkbox/angular/input-checkbox.component.html
  projects/front-end-library/src/lib/components/input-checkbox/angular/input-checkbox.component.ts
  projects/front-end-library/src/lib/components/input-checkbox/angular/input-checkbox.module.ts
  projects/front-end-library/src/lib/components/input-checkbox/scss/index.scss
  projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
  projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
  projects/front-end-library/src/lib/scss/index.scss
  projects/front-end-library/src/lib/scss/themes/videotron/_color.scss
  projects/front-end-library/src/public-api.ts
Labels: tested

#271 DS-283-text-featured
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/text-featured/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/text-featured/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/text-featured/angular/text-featured.component.html
  projects/front-end-library/src/lib/components/text-featured/angular/text-featured.component.ts
  projects/front-end-library/src/lib/components/text-featured/angular/text-featured.module.ts
  projects/front-end-library/src/lib/components/text-featured/twig/index.twig
Labels: tested

#142 DS-114: Added isRequired as attribute in input-increment
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/input-increment/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/input-increment/_doc/template.drupal.twig
  projects/front-end-library/src/lib/components/input-increment/angular/input-increment.component.ts
  projects/front-end-library/src/lib/components/input-increment/twig/index.twig
Labels: tested

#305 DS-312 - fixed height logo with breakpoints
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/logo/scss/index.scss
  projects/front-end-library/src/lib/components/logo/twig/index.twig
  projects/front-end-library/src/lib/components/navigation-header/scss/index.scss
  projects/front-end-library/src/lib/components/navigation-header/twig/index.twig
Labels: tested

#306 DS-331 - Tab Full width bottom border
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/tab/scss/index.scss
Labels: tested

#230 DS 241 update props to argstable
  projects/front-end-library/src/lib/_doc/1-Introduction/4-merge-checklist.stories.mdx
  projects/front-end-library/src/lib/_doc/1-Introduction/5-components-list.stories.mdx
  projects/front-end-library/src/lib/_doc/2-Implementation/3-angular.stories.mdx
  projects/front-end-library/src/lib/_doc/2-Implementation/5-drupal-filters.stories.mdx
  projects/front-end-library/src/lib/_doc/migrations/1-icon-migration.stories.mdx
  projects/front-end-library/src/lib/_doc/styles/5-icons/icons.stories.mdx
  projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/banner/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/block-highlight/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/block-selection/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/breadcrumb/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/button-icon/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/button-nav/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/card/_doc/plan-api-exposed.stories.mdx
  projects/front-end-library/src/lib/components/carousel/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/hero/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/icon/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/iframe-video/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/image-lazy-load/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/input-checkbox/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/input-increment/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/input-radio/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/input-search/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/input-slider/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/link/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/list/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/logo/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/navigation-footer/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/navigation-header/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/price/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/progress-multi/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/progress/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/row-button/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/selection-tile/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/slideshow/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/status/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/tab/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/text-featured/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/tile-post/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/components/tile/_doc/doc.stories.mdx
  scripts/generate/templates/component/_doc/doc.stories.mdx
Labels: Ready for review, On hold

#237 DS-253 init section keys (features List)
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/button/angular/api.model.ts
  projects/front-end-library/src/lib/components/link/angular/api.model.ts
  projects/front-end-library/src/lib/components/link/scss/index.scss
  projects/front-end-library/src/lib/scss/index.scss
  projects/front-end-library/src/lib/sections/keys/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/sections/keys/_doc/template.drupal.twig
  projects/front-end-library/src/lib/sections/keys/angular/section-keys.component.html
  projects/front-end-library/src/lib/sections/keys/angular/section-keys.component.ts
  projects/front-end-library/src/lib/sections/keys/angular/section-keys.module.ts
  projects/front-end-library/src/lib/sections/keys/scss/index.scss
  projects/front-end-library/src/lib/sections/keys/twig/index.twig
Labels: tested

#299 ds-325 fix link isUnderline
  CHANGELOG.mdx
  projects/front-end-library/src/lib/components/link/twig/index.twig
Labels: tested

#312 ds-343 move UI Kit section at the bottom of the sidebar
  .storybook/preview.ts
Labels: tested

#310 ds-252 fix section tiles post
  projects/front-end-library/src/lib/sections/tiles-post/_doc/doc.stories.mdx
  projects/front-end-library/src/lib/sections/tiles-post/_doc/template.drupal.twig
  projects/front-end-library/src/lib/sections/tiles-post/angular/section-tiles-post.component.ts
  projects/front-end-library/src/lib/sections/tiles-post/twig/index.twig
Labels: tested
